"""One-page markdown autopsy report for a probe agent run."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from aorta.agent.state import AgentState

_REPORT_NAME = "agent_report.md"


def write_agent_report(
    run_dir: Path,
    *,
    state: AgentState,
    cell_summaries: list[dict[str, Any]],
    outcome: str,
    recommended_action: str,
) -> Path:
    """Write ``agent_report.md`` under the ticket run directory."""
    lines: list[str] = []
    lines.append("# Aorta Probe Agent — Autopsy Report")
    lines.append("")
    lines.append(f"- **Ticket:** `{state.ticket}`")
    lines.append(f"- **Outcome:** {outcome}")
    lines.append(f"- **Category:** `{state.last_category}`")
    if state.winning_mitigation:
        lines.append(f"- **Winning mitigation:** `{state.winning_mitigation}`")
    lines.append(f"- **Iterations:** {state.iterations_completed}")
    lines.append("")
    lines.append("## Hypothesis")
    lines.append("")
    lines.append(state.last_hypothesis or "_No hypothesis recorded._")
    lines.append("")
    lines.append("## Mitigation search tree")
    lines.append("")
    if not cell_summaries:
        lines.append("_No cells executed._")
    else:
        lines.append("| Cell | Verdict | Detectors |")
        lines.append("|------|---------|-----------|")
        for row in cell_summaries:
            cell = row.get("cell_name", "?")
            verdict = row.get("verdict", "?")
            detectors = row.get("failure_detectors_fired") or []
            det_str = ", ".join(detectors) if detectors else "—"
            lines.append(f"| `{cell}` | {verdict} | {det_str} |")
    lines.append("")
    lines.append("## Evidence chain")
    lines.append("")
    any_capture = False
    for row in cell_summaries:
        capture = row.get("capture") or {}
        if not capture:
            continue
        any_capture = True
        lines.append(f"- **{row.get('cell_name')}** capture: `{capture}`")
    if not any_capture:
        lines.append("_No capture fields recorded._")
    lines.append("")
    lines.append("## Recommended next action")
    lines.append("")
    lines.append(recommended_action)
    lines.append("")
    lines.append("---")
    lines.append("_Generated by `aorta agent`. Verdicts are from the deterministic probe classifier._")

    path = run_dir / _REPORT_NAME
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


__all__ = ["write_agent_report"]
