"""BUCK file-fragment emitter for ``aorta env recipe --format buck``.

Reads an env.json snapshot (already loaded into a dict) and emits a
text fragment containing one ``prebuilt_cxx_library`` rule per
``library_introspection`` entry whose ``source == "buck"``. Entries
from other sources (``pkg-config``, ``elf``, etc.) are skipped --
this recipe is Buck-flavour only and a non-Buck library has no Buck
target to point at.

Per the issue spec (#163, A1.2c):

* Output is BEST-EFFORT, NOT EXACT. The loud header explains why.
* Pure text generation -- no subprocess, no I/O, never raises on
  shape variation. A missing field renders as a ``# unknown <field>``
  comment so the operator sees the gap rather than a Python
  exception.
* No Buck rule / macro library vendored. We emit plain
  ``prebuilt_cxx_library`` calls and let the user's Buck instance
  resolve them.

The CLI entry point is in :mod:`aorta.cli.env` and lives next to
``aorta env probe``.
"""

from __future__ import annotations

from typing import Any

# Loud header documenting the recipe's limitations. Required by the
# A1.2c acceptance criterion: "Output starts with the loud
# 'BEST-EFFORT, NOT EXACT' comment block."
RECIPE_HEADER = """\
# ============================================================================
# AUTO-GENERATED BY `aorta env recipe --format buck` -- BEST-EFFORT, NOT EXACT.
# env.json captures observed state, not a complete build recipe. Internal
# targets, host-coupled driver state, mounted source trees, local patches,
# and private toolchains are not recoverable from observation. Use as a
# starting point.
# ============================================================================
"""


def emit_buck_recipe(env: dict[str, Any]) -> str:
    """Render a BUCK file fragment from an env.json snapshot dict.

    The fragment is always prefixed with :data:`RECIPE_HEADER` so an
    operator who pipes the output into a Buck file sees the
    "BEST-EFFORT" warning at the top.

    The body contains:

    * A ``# build_system: ...`` provenance comment summarising the
      captured Buck2 environment (or ``kind=none`` when env.json was
      captured outside a Buck checkout -- in which case the fragment
      will likely have no rules, just the header + a provenance hint).
    * One ``prebuilt_cxx_library(...)`` per ``library_introspection``
      entry with ``source == "buck"``. Each rule pins the captured
      ``revision`` as a ``version`` attribute and includes the original
      Buck ``target`` as a ``# original_target = ...`` comment so the
      consumer can trace back to env.json.
    * A trailing ``# library_introspection_alternates`` block (when
      non-empty) listing every A1-side alternate that was dropped when
      the Buck entry won the merge, as comments only (no rules). Aids
      the operator diffing against a non-Buck reference snapshot.

    Never raises. A malformed env.json (missing keys, wrong types) is
    surfaced as ``# <warning>`` comments rather than an exception, so
    the recipe is still inspectable.
    """
    out: list[str] = [RECIPE_HEADER]

    # Guard against env.json that carries a non-dict ``build_system``
    # (hand-edited file, schema regression, future-version field with
    # an unexpected shape). The emitter's "never raises" contract means
    # we surface the violation as a recipe-visible warning rather than
    # letting ``.get(...)`` raise AttributeError. Per Copilot review on
    # PR #178.
    raw_build_system = env.get("build_system")
    if raw_build_system is None:
        build_system: dict[str, Any] = {"kind": "unknown"}
    elif isinstance(raw_build_system, dict):
        build_system = raw_build_system
    else:
        out.append(
            f"# warning: build_system has unexpected type "
            f"{type(raw_build_system).__name__}; expected dict. "
            f"Treating as kind=unknown."
        )
        build_system = {"kind": "unknown"}
    out.append(_build_system_comment(build_system))

    introspection = env.get("library_introspection") or []
    if not isinstance(introspection, list):
        out.append(
            f"# warning: library_introspection has unexpected type "
            f"{type(introspection).__name__}; expected list. "
            f"No rules will be emitted."
        )
        introspection = []

    buck_entries = [
        e for e in introspection
        if isinstance(e, dict) and e.get("source") == "buck"
    ]

    if not buck_entries:
        out.append(
            "# library_introspection contains no source=buck entries; "
            "the fragment below is empty. Re-run `aorta env probe` with "
            "`--buck-target <label>` inside a Buck checkout to populate "
            "this section."
        )
    else:
        out.append("")
        out.append(f"# {len(buck_entries)} buck-introspected librar"
                   f"{'ies' if len(buck_entries) != 1 else 'y'}:")
        for entry in buck_entries:
            out.append("")
            out.append(_render_prebuilt_cxx_library(entry))

    alternates = env.get("library_introspection_alternates") or []
    if isinstance(alternates, list) and alternates:
        out.append("")
        out.append(_render_alternates_comment_block(alternates))

    # Trailing newline so concatenation into a larger BUCK file is clean.
    return "\n".join(out) + "\n"


def _build_system_comment(build_system: dict[str, Any]) -> str:
    """One-line provenance comment describing the captured build_system."""
    kind = build_system.get("kind") or "unknown"
    if kind != "buck2":
        return (
            f"# build_system: kind={kind} -- env.json was NOT captured "
            f"inside a Buck checkout, so the emitted fragment may be "
            f"empty or only reflect manually-set library_introspection "
            f"entries."
        )
    version = build_system.get("buck2_version") or "unknown"
    repo_root = build_system.get("repo_root") or "unknown"
    revision = build_system.get("revision") or "unknown"
    return (
        f"# build_system: kind=buck2 buck2_version={version} "
        f"repo_root={repo_root} revision={revision}"
    )


def _render_prebuilt_cxx_library(entry: dict[str, Any]) -> str:
    """Render one ``prebuilt_cxx_library(...)`` call from a Buck entry."""
    name = entry.get("name") or "unknown"
    target = entry.get("target") or "unknown"
    revision = entry.get("revision")
    revision_attr = (
        f'    version = "{revision}",'
        if revision
        else "    # version omitted: revision unknown in source env.json"
    )
    # Per the issue spec's open question Q2 ("source-built vs binary-
    # pinned"): the spec defers and says "emit prebuilt_cxx_library
    # only with a comment noting the limitation". So we always emit
    # prebuilt_cxx_library and include the trailing limitation comment.
    return (
        f"# original_target = {target}\n"
        f"prebuilt_cxx_library(\n"
        f'    name = "{name}",\n'
        f"{revision_attr}\n"
        f"    # NOTE: emitted as prebuilt_cxx_library because env.json\n"
        f"    # captures the resolved binary, not the source-build recipe.\n"
        f"    # If this library is source-built in your Buck setup,\n"
        f"    # swap for cxx_library and add the appropriate srcs/headers.\n"
        f")"
    )


def _render_alternates_comment_block(alternates: list[dict[str, Any]]) -> str:
    """Format ``library_introspection_alternates`` as a comment block.

    Alternates are A1-side entries that lost a merge against a Buck
    match. They have no Buck target so they can't be rendered as
    rules; we surface them as comments only so an operator diffing
    this recipe against a non-Buck snapshot can see what was dropped.
    """
    lines = [
        "# library_introspection_alternates (informational, "
        "no rules emitted):"
    ]
    for alt in alternates:
        if not isinstance(alt, dict):
            lines.append(
                f"#   - <malformed entry, expected dict, got "
                f"{type(alt).__name__}>"
            )
            continue
        name = alt.get("name") or "?"
        source = alt.get("source") or "?"
        revision = alt.get("revision") or "?"
        dropped_for = alt.get("dropped_for") or "?"
        lines.append(
            f"#   - {name}: source={source} revision={revision} "
            f"(dropped for source={dropped_for})"
        )
    return "\n".join(lines)
